spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jimiarts
    username: jimiarts
    password: jimiarts
  jpa:
    hibernate:
      ddl-auto: 'create'
